Career26/frontend

- public/CNAME
> Adds cname

- src/features/app/App.tsx
- src/features/careerTest/CareerTest.tsx
- src/shared/components/account/LoginModal.tsx
- src/shared/hooks/useAuthUser.ts
- handles associate profile
- fetches profile after associate complete
- sends notification in profile gen has error
> Bug - Signup flow

- package.json
> Updates build

- src/features/app/App.tsx
- src/features/careerTest/CareerTest.tsx
- src/index.tsx
- SPA not supported in GH Pages using BrowserRouter
- Swaps to HashRouter
> Uses hash router for GH Pages

- src/datatypes/overview.ts
- src/features/careerTest/config/formConstants.ts
- src/features/overview/OverviewPage.tsx
- src/features/overview/tiles/RoleSummaryTile.tsx
- src/mocks/overviewMocks.ts
- src/shared/components/account/LoginModal.tsx
- src/shared/components/loadingScreen/LoaderWithText.tsx
- src/shared/components/loadingScreen/TypeWriter.tsx
- src/shared/components/loadingScreen/loadingTypes.ts
- src/shared/components/pageHeader/CareerNavigation.tsx
- updates role summary for the breakdown of
```
export interface RoleSummary {
responsibilities: string;
dayToDay: string;
skills: string;
personalityType: string;
}
```
> Role summary breakdown

- src/features/careerTest/components/diversityForm/DiversityForm.tsx
- src/features/careerTest/components/diversityForm/SelectHousehold.tsx
- src/features/careerTest/components/educationForm/UniversityForm.tsx
- src/features/careerTest/components/workExperienceForm/ExperienceForm.tsx
- on focus will dropdown select options
> Allows searchable select

- package.json
- src/features/careerTest/CareerTest.tsx
- src/features/settings/ProfileTab.tsx
- includes favicon in build
- allows users to retake tests
- fixes gender display on account info
> UI Enhancements

- public/index.html
> Adds Google Analytics

- package-lock.json
- package.json
- src/features/careerTest/CareerTest.tsx
- src/features/settings/ProfileTab.tsx
- src/shared/components/account/LoginModal.tsx
Does not ask for gender for signup - in line with BE
> No gender on sign up

- package-lock.json
- package.json
- src/shared/components/pageHeader/CareerNavigation.tsx
- src/shared/components/pageHeader/PageHeader.tsx
- src/shared/components/pageHeader/headerStyles.module.scss
> Fixes career nav click

- src/shared/config/urlConstants.ts
- client pool and id changed, updates urls
> Updates new urls

- src/features/careerTest/CareerTest.tsx
- src/features/careerTest/components/careerTestHeader/CareerTestHeader.tsx
- src/features/careerTest/components/careerTestHeader/careerTestHeader.module.scss
- src/features/interview/QuestionNavBar.tsx
- src/features/overview/OverviewPage.tsx
- src/features/overview/tiles/RoleSummaryTile.tsx
- src/features/settings/ProfileTab.tsx
- src/features/settings/settingsStyles.module.scss
- src/shared/components/account/LoginModal.tsx
- src/shared/components/account/SignUpBenefits.tsx
- src/shared/components/account/accountStyles.module.scss
- src/shared/components/pageHeader/CareerNavigation.tsx
- src/shared/components/pageHeader/NavigationCenter.tsx
- src/shared/components/pageHeader/PageHeader.tsx
- src/shared/components/pageHeader/headerStyles.module.scss
- src/shared/components/shell/Shell.tsx
- src/shared/hooks/useActiveNavScroll.ts
- src/shared/hooks/useMobileStyles.ts
- src/shared/styles/commonStyles.module.scss
- Adds mobile styles
- tested in Chrome
next steps to update in Safari
> Mobile styling

- src/features/careerTest/CareerTest.tsx
- clicking back when complete takes to step 3
- clears cache before creating profile
> Fixes click back on career test

- src/shared/components/pageHeader/CareerNavigation.tsx
- src/shared/components/pageHeader/PageHeader.tsx
- src/shared/components/pageHeader/headerStyles.module.scss
> Always show logo

- src/features/app/App.tsx
- src/features/careerTest/components/careerTestHeader/CareerTestHeader.tsx
- src/features/careerTest/components/careerTestHeader/careerTestHeader.module.scss
- src/features/careerTest/components/educationForm/UniversityForm.tsx
- src/features/careerTest/components/preferencesForm/WorkStyleForm.tsx
- src/features/careerTest/components/workExperienceForm/ExperienceForm.tsx
- src/features/homePage/homePageStyles.module.scss
- src/features/settings/ProfileTab.tsx
- src/features/settings/settingsStyles.module.scss
- src/shared/components/display/TextWithIconBlock.tsx
- src/shared/components/pageHeader/CareerNavigation.tsx
- src/shared/components/pageHeader/NavigationCenter.tsx
- src/shared/components/pageHeader/PageHeader.tsx
- src/shared/components/pageHeader/headerStyles.module.scss
- src/shared/styles/commonStyles.module.scss
- src/state/apis/profileApi.ts
- src/state/apis/questionsApi.ts
This reverts commit e31e12614dc25c0ad119e5a0723f8986a9fd3d0d.
> Revert "Updates mobile styles (#97)"

- src/shared/components/loadingScreen/LoadingLens.tsx
- src/shared/components/pageHeader/IconButtons.tsx
- src/shared/components/pageHeader/NavigationCenter.tsx
- src/shared/components/pageHeader/PageHeader.tsx
- src/shared/components/pageHeader/headerStyles.module.scss
- src/shared/styles/commonStyles.module.scss
- logo centered on mobile safari
- logo size reduced on loading lens
- has the same nav centre pop up for desktop and mobile
> Updates styles for safari

- src/datatypes/feedback.ts
- src/features/app/App.tsx
- src/features/careerTest/components/educationForm/UniversityForm.tsx
- src/features/careerTest/components/workExperienceForm/ExperienceForm.tsx
- src/shared/components/feedback/FeedbackForm.tsx
- src/shared/components/feedback/FeedbackModal.tsx
- src/shared/components/feedback/feedback.module.scss
- src/shared/components/feedback/feedbackConstants.ts
- src/shared/components/pageFooter/PageFooter.tsx
- src/shared/components/pageFooter/pageFooter.module.scss
- src/shared/components/shell/Shell.tsx
- src/shared/components/shell/shellStyles.module.scss
- src/shared/config/urlConstants.ts
- src/shared/utils/formUtil.ts
- src/state/slices/sessionSlice.ts
Page footer with
- linked in link
- feedback form
- contact us
> Adds page footer

- src/shared/components/account/LoginModal.tsx
Fixes mobile styling for signup
> Fixes mobile styling for signup

- src/features/careerTest/CareerTest.tsx
- src/features/homePage/HomePage.tsx
- src/features/homePage/homePageStyles.module.scss
- src/shared/components/pageHeader/NavigationCenter.tsx
- adds disabled tiles back in
- adds 'retake test' in career test button labels
> Updates to ux

- src/shared/components/feedback/FeedbackModal.tsx
- src/shared/components/pageFooter/PageFooter.tsx
- src/shared/config/urlConstants.ts
- src/state/apis/feedbackApi.ts
- src/state/store.ts
Adds feedback and new user pool
> Feedback dialog

- src/features/careerTest/CareerTest.tsx
- src/features/settings/SettingsPage.tsx
- src/features/settings/UserInfoTab.tsx
- src/shared/components/account/LoginModal.tsx
- src/shared/hooks/useAssociate.ts
Associates profile bug fix on save
> Fixes associate profile
